---
- name: Installation des modules pythons pour dropbox
  pip:
    name: dropbox
    state: latest
  tags:
    - dropboxwatcher

- name: Copie du fichier de service dropboxwatcher
  template:
    src: dropboxwatcher.service.j2
    dest: /etc/systemd/system/dropboxwatcher.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart seedbox services
  tags:
    - dropboxwatcher

- name: Création du dossier de dropboxwatcher
  file:
    path: "{{ seedbox_dropboxwatcher_path }}"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  tags:
    - dropboxwatcher

- name: Copie du fichier de configuration dropboxwatcher
  template:
    src: dropboxwatcher.cfg.j2
    dest: "{{ seedbox_dropboxwatcher_path }}/dropboxwatcher.cfg"
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0644
  notify:
    - restart seedbox services
  tags:
    - dropboxwatcher

- name: Copie du script dropboxwatcher
  copy:
    src: dropboxwatcher.py
    dest: "{{ seedbox_dropboxwatcher_path }}"
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  notify:
    - restart seedbox services
  tags:
    - dropboxwatcher

- name: Création du dossier de watch
  file:
    path: "{{ seedbox_watch_folder_path }}"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  tags:
    - dropboxwatcher
