---
# Installation des packages requis

- include: packages.yml

# Création de l'utilisateur seedbox

- include: user.yml

# Installation du vpn

- include: openvpn.yml

# Installation du service rtorrent

- include: rtorrent.yml
