---
# Installation des packages requis

- include: packages.yml

# Installation du vpn

- include: openvpn.yml

# Installation du service dropboxwatcher

- include: dropboxwatcher.yml

# Installation du service rtorrent

- include: rtorrent.yml
