---
# Installation des packages requis

- include_vars: "{{ ansible_os_family }}.yml"
- include_tasks: "packages-{{ ansible_os_family }}.yml"

# Création de l'utilisateur seedbox

- import_tasks: user.yml

# Installation du vpn

- import_tasks: openvpn.yml

# Installation du service rtorrent

- import_tasks: rtorrent.yml

# Installation du crontab pour youtube-dl

- import_tasks: youtube-dl.yml
