---
- name: Mise en place du service openvpn
  template:
    src: openvpn@.service.j2
    dest: /etc/systemd/system/openvpn@.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon-reload
  tags:
    - openvpn

- name: Copie des fichiers openvpn
  copy:
    src: "{{ seedbox_openvpn_configs_dir }}"
    dest: "/etc/openvpn/{{ seedbox_user }}"
  notify:
    - restart rtorrent
  tags:
    - openvpn
