---
- name: Installation du repository epel
  yum:
    name: epel-release
    state: latest
  tags:
    - pkgs
    - openvpn
    - rtorrent

- name: Installation des packages requis
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ seedbox_pkgs }}"
  tags:
    - pkgs
    - openvpn
    - rtorrent
    - youtube_dl

- name: Installation des packages pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{ seedbox_pip_pkgs }}"
  tags:
    - pkgs
    - youtube_dl
