---
- name: Mise en place du service rtorrent
  template:
    src: rtorrent@.service.j2
    dest: /etc/systemd/system/rtorrent@.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd daemon-reload
  tags:
    - rtorrent

- name: Mise en place du fichier de configuration rtorrent
  template:
    src: rtorrent.rc.j2
    dest: "/home/{{ seedbox_user }}/.rtorrent.rc"
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0644
  notify:
    - restart rtorrent
  tags:
    - rtorrent

- name: Création du dossier de téléchargement en cours
  file:
    path: "{{ seedbox_download_folder }}/incomplete/"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  tags:
    - rtorrent

- name: Création des dossiers de téléchargements finaux
  file:
    path: "{{ seedbox_download_folder }}/{{ item[0] }}/{{ item[1] }}/"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  with_nested:
    - complete
    - "{{ seedbox_watch_folders }}"
  tags:
    - rtorrent

- name: Création du dossier du script de démarrage rtorrent
  file:
    path: "{{ seedbox_rtorrentlauncher_path }}"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  tags:
    - rtorrent

- name: Copie du script de démarrage de démarrage rtorrent
  copy:
    src: rtorrent.sh
    dest: "{{ seedbox_rtorrentlauncher_path }}"
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  notify:
    - restart rtorrent
  tags:
    - rtorrent

- name: Copie du script de relance automatique
  template:
    src: rtorrentCheck.sh.j2
    dest: "{{ seedbox_rtorrentlauncher_path }}/rtorrentCheck.sh"
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  notify:
    - restart rtorrent
  tags:
    - rtorrent

- name: Mise en place d'un cron pour la relance automatique
  cron:
    job: "{{ seedbox_rtorrentlauncher_path }}/rtorrentCheck.sh"
    name: "Check that rtorrent binding to vpn is correct"
    user: "{{ seedbox_user }}"
  notify:
    - restart crond service
  tags:
    - rtorrent

- name: Mise en place d'une autorisation de relancer le service
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^rtorrent"
    line: "{{ item }}"
    state: present
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  with_items:
    - "rtorrent ALL= NOPASSWD: /bin/systemctl * rtorrent*"
    - "rtorrent ALL= NOPASSWD: /bin/systemctl * dropboxwatcher"
  tags:
    - rtorrent
