---
- name: Création de l'utilisateur pour la seedbox
  user:
    name: "{{ seedbox_user }}"
    state: present
  tags:
    - rtorrent
    - openvpn
    - youtube_dl

- name: Création des dossiers
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ seedbox_user }}"
    group: "{{ seedbox_user }}"
    mode: 0755
  with_items:
    - "{{ seedbox_scripts_path }}"
    - "{{ seedbox_download_folder }}/incomplete/"
    - "{{ (seedbox_watch_folders + ['Youtube-dl']) | map('regex_replace', '(.*)', seedbox_watch_folder_path + '/\\1') | list }}"
    - "{{ (seedbox_watch_folders + ['Youtube-dl']) | map('regex_replace', '(.*)', seedbox_download_folder + '/complete/\\1') | list }}"
    - "{{ seedbox_session_folder_path }}"
  tags:
    - rtorrent
    - openvpn
    - youtube_dl

- name: Mise en place des droits sudo pour la relance du service
  lineinfile:
    dest: "/etc/sudoers"
    regexp: "^rtorrent"
    line: "rtorrent ALL= NOPASSWD: /bin/systemctl * rtorrent*"
    state: present
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  tags:
    - rtorrent

