---
# handlers file for seedbox
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart dropboxwatcher
  systemd:
    name: dropboxwatcher
    state: restarted

- name: restart rtorrent
  shell: "{{ seedbox_rtorrentlauncher_path }}/rtorrentCheck.sh restart"

- name: restart crond service
  service:
    name: crond
    state: restarted
    enabled: yes
